apiVersion: v1
kind: Service
metadata:
  name: {{ include "vam.fullname" . }}
  labels:
    {{- include "vam.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: guestbook
    {{- include "vam.selectorLabels" . | nindent 4 }}
